### ISSUE TITLE
how do I remove generated options? 

### ISSUE THREAD

**Issue by nyczus** [alfg/ffmpeg-commander#19]
Hi, I have a little problem because when I use FFmpeg with generated options It won't download, for example "-ss -to" parameter has to be at the beginning of the code in order for it to work (ffmpeg.exe -to 00:00:00 -ss 00:00:00 -i "file.m3u8" -c copy -bsf:a aac_adtstoasc "output.mp4" and I have to edit it manually. Is there any way to completely remove generated options? And set custom ones? Thanks

**Comment by alfg** [comment]
Hey @nyczus, 

Sorry, setting custom options or removing generated options are not supported.
