### ISSUE TITLE
PAL 625i preset

### ISSUE THREAD

**Issue by sfahadshahzad** [alfg/ffmpeg-commander#20]
Can you please add input and out preset for DV PAL / SD (720x576) cause having issues when getting input from PAL 625i and out to same resolution.

I think it is due to interlace input issue when encoding into h264 with same resolution.

The out is Having flicker / combing.

Fahad

**Comment by alfg** [comment]
Hi @sfahadshahzad, 

Not sure I'm following. Are you asking to add a preset, or another resolution/aspect option? If so, do you have an example of the ffmpeg command options to add?

**Comment by alfg** [comment]
Closing. Feel free to respond with clarification. Thanks.
