### ISSUE TITLE
X265/HEVC 2 pass options

### ISSUE THREAD

**Issue by OFark** [alfg/ffmpeg-commander#21]
According to the documentation pass 1 and pass 2 should be part of the -x265-params not part of the general options:

> For two-pass, you need to run ffmpeg twice, with almost the same settings, except for:
> In pass 1 and 2, use the -x265-params pass=1 and -x265-params pass=2 options, respectively.

**Comment by alfg** [comment]
Ah, good catch! I'll fix this soon. Thanks!

**Comment by alfg** [comment]
Fixed on latest build.
