### ISSUE TITLE
Can this tool generate a command to add watermark?

### ISSUE THREAD

**Issue by wf58585858** [alfg/ffmpeg-commander#22]
`ffmpeg -i input.mp4 -i logo.png -filter_complex 'overlay=x=10:y=main_h-overlay_h-10' output.mp4`

I found a command that others can test, but ffmpeg prompts ` no such filter: 'overlay = x = 10: y = main_ h-overlay_ h-10'`
Can this tool generate a command to add watermark?
What should be the correct command to add watermark? thanks

**Comment by wf58585858** [comment]
version:
ffmpeg version 2021-10-24-git-9df3f147f5-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 11.2.0 (Rev1, Built by MSYS2 project)

**Comment by alfg** [comment]
No, not currently. The filters are limited to some of the basic options at this time.
