### ISSUE TITLE
can't connect to ffmpegd

### ISSUE THREAD

**Issue by stp6778** [alfg/ffmpeg-commander#26]
Hi,

I've build an alpine docker image with ffmepg, ffmpegd and ffmpeg-commander.
I've enabled ffmpegd option but  it always show offline status.

ffmpegd seems running ok, curl localhost:8080 displays dirlist from current started directory. 
I dont understand what i miss !

Thanks for help.

**Comment by alfg** [comment]
Hey @stp6778, 

Which browser are you using? Can you check the devtools console and see if there's any error outputted?

I tried a fresh install using: `docker run -it -p 8080:8080 -v /tmp/:/home alfg/ffmpegd` and it seems to work for me using Firefox on https://alfg.github.io/ffmpeg-commander with the ffmpegd option enabled. 

Thanks.

**Comment by stp6778** [comment]
Hi,

I understand my problem when you told me to use the console : your browser is running on same machine.

Mine is running on a windows PC and my docker containers on a nuc server.
So I set my nuc hostname in ffmpegd.go and websocket.js, FileBrowser.vue, Queue.vue and now it works !

It seems that progress bar not update and cancel job don't kill ffmpeg process.

It would  be convenient to have docker variable to define the working hostname and input, output basedir.

Thanks or this nice tool.

**Comment by alfg** [comment]
Added #27 as a TODO to add the suggestion. Thanks @stp6778.
