### ISSUE TITLE
Where AV1?

### ISSUE THREAD

**Issue by RUNETHERABB1T** [alfg/ffmpeg-commander#36]
As the title says where is AV1? The command is just "-c:v libsvtav1" so im slightly confused by why its not there

**Comment by gmillerd** [comment]
This is not a comprehensively incorporate all known and libraries. Which is addressed in the readme, eg simple/common. That's likely the "why".

As far as "is just" a drop in the "cv", It also has a significantly different config for the the library options. Much like vp9 vs h264 or similar.

**Comment by alfg** [comment]
As @gmillerd mentioned, I am only supporting simple and common options. Currently av1 is supported via `libaom-av1`.
