### ISSUE TITLE
Publish ffmpeg-commander as docker image

### ISSUE THREAD

**Issue by drandarov-io** [alfg/ffmpeg-commander#43]
Hi, could you kindly expand the GitHub Action workflow with an push of the docker image to your packages similar to `ffmpegd`?
I'd like to deploy it to an environment where I can't build images and I'd rather use an "official" image than host a separate registry.

**Comment by alfg** [comment]
Hey @drandarov-io, 

I pushed up an image to master at:
https://github.com/alfg/ffmpeg-commander/pkgs/container/ffmpeg-commander

Can you try running with:
```
docker run -it -p 8080:80 ghcr.io/alfg/ffmpeg-commander:master
```

And loading in the browser:
http://localhost:8080/ffmpeg-commander/

**Comment by drandarov-io** [comment]
Works great except that I misread `8080:80` as `8080:8080` first. 😅
The only thing I noticed is that path `/` could automatically redirect to `/ffmpeg-commander/`, but that would be a separate issue.

**Comment by alfg** [comment]
Thanks for checking! I also need to start versioning and tagging this properly as well, but I'll add that in another update.
